language: scala
jdk:
  - oraclejdk8
script:
  - sbt "testOnly -- *$PROJECT"
cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.nvm
before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
env:
  matrix:
    - PROJECT=algebra
    - PROJECT=betterfiles
    - PROJECT=scalacheck
    - PROJECT=ScalaPB
    - PROJECT=scalatest
    - PROJECT=scopt
    - PROJECT=squants
    - PROJECT=collectionstrawman
